---
- name: Install dependencies untuk Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install Docker Engine dan Compose Plugin
  apt:
    name:
      - docker.io
      - docker-compose-v2  # Ini yang paling penting untuk memperbaiki error tadi
    state: present
    update_cache: yes

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled